<html>

    <head>
    <meta charset="utf-8" />
	   <title>Zooland - Un voyage en terre inconnue</title>
	   <link rel="stylesheet" type="text/css" href="css/estil.css" />
	</head>
    <body>
        <div id="bloc_page">
            <header>
                <div id="titre_principal">
                    <div id="logo">
                        <img src="images/zooland_logo.png" alt="Logo de Zooland" />
                        <h1>Zooland</h1>    
                    </div>
                    <h2>Un voyage en terre inconnue</h2>
                </div>
                <nav>
                    <ul>
                        <li><a href="index.phtml">Accueil</a></li>
                        <li><a href="actualité.phtml">Actualité</a></li>
                        <li><a href="animaux.phtml">Animaux</a></li>
						<li><a href="activités.phtml">Activités</a></li>
                        <li><a href="contact.phtml">Contact</a></li>
                    </ul>
                </nav>
            </header>
            <div class="banniere_image">
                <img src="images/activité.png" alt="des espèces rares de toute la planète" >
                <div id="banniere_description">
                     
                    <p>Un parcours de découverte, des activités pour toute la famille.</p>

                    
                </div>
            </div>
			<form method="post" action="traitement.php">
				   <p>
				       <label for="pseudo">Votre pseudo :</label>
				       <input type="text" name="pseudo" id="pseudo" />
				       
				       <br />
				       <label for="pass">Votre mot de passe :</label>
				       <input type="password" name="pass" id="pass" />
				       
				   </p>
			</form>
			
            
            <section>
                <article>
                    <h1><img src="images/arbre.jpg" alt="x" class="ico_categorie" /><u>Des spectacles</u></h1>
                    <p>Les soigneurs vous proposent chaque jour des représentations avec les animaux. Ces représentations vous révèlent non seulement les aptitudes et particularités de chacune des espèces mais répondent surtout au besoin de stimulations physique et mentale de ces animaux hors du commun.  C’est également un moment privilégié entre les soigneurs et les animaux lors duquel la relation qui les lie ne pourra pas vous échapper… Le terme de soigneur  signifie d’ailleurs : prendre soin !</p>
                    <p><strong><u>Spectacle d'oiseaux "Les maitres des airs" :</u></strong></p>
                    <p>Le temps fort de votre journée au Parc ! Avec ce spectacle d’oiseaux en vol, vous assistez depuis les gradins à un ballet féérique de grâce et de couleurs..
                    Ces représentations sont le fruit du travail passionné des soigneurs qui entraînent pélicans, grues, marabouts d’Afrique, calaos terrestres, perroquets de diverses espèces, sublimés dans leur dimension mythique : le VOL.</p>
                    <p>Vous serez enchantés par la diversité des espèces qui effectuent cette danse aérienne et légère en déployant leurs ailes.</p>
                    <p>Un spectacle qui reflète la complicité et la confiance que les soigneurs ont développées avec les oiseaux dès leur naissance. En effet la distribution de ce spectacle est composée d’oiseaux nés au parc. Le bien-être et les spécificités de chaque espèce sont respectés. Un spectacle majestueux accompagné d’un commentaire didactique qui reflète les valeurs du Parc et témoigne d’une volonté pédagogique de sensibiliser le public à la fragilité de l’avifaune.</p>
                    <p><strong><u>Spectacle d'otaries "L'Odyssée des lions de mer" :</u></strong></p>
                    <p>Dans le plus fabuleux complexe aquatique de France, les otaries de Patagonie prouvent une nouvelle fois leur sens inné du jeu et de la comédie. Le spectacle des otaries de Patagonie est particulièrement apprécié des visiteurs. Ils découvrent ainsi ces magnifiques mammifères marins dotés d’une intelligence rare. Les otaries sont capables de comprendre des signaux rapidement et ébahissent le public par leur dextérité. Elles possèdent aussi un sens inné du jeu et de la comédie, et font le spectacle pour le plus grand plaisir des petits et des grands. Les mâles de couleur brun-sombre peuvent atteindre une taille de 2,5 mètres environ, de quoi impressionner les familles venues nombreuses à chaque représentation. Les otaries évoluent dans le plus grand complexe aquatique d’Europe. Un lieu privilégié pour contempler ces spectacles d’otaries. </p>
                    <p>Les visiteurs ayant envie d’en connaître davantage sur ces mammifères marins pourront poser des questions aux soigneurs lors du gouter proposé avec les phoques et les otaries. N’attendez plus pour venir découvrir ce spectacle incontournable du PAL et admirer aussi les 700 animaux du parc évoluant sur 50 hectares d’une nature luxuriante !</p>
                    <p><strong><u>Animation pédagogique "Apprendre au zoo parc" :</u></strong></p>
                    <p>Quotidiennement un soigneur de notre parc propose une visite guidée du parc et de ses installations. Le principe est de se laisser guider pour apprendre de nos amis les animaux grâce à ceux qui les cotoies tous les jours.</p>
                    <p><strong><u>Spectacle de perroquets "Le carnaval des plumes" :</u></strong></p>
                    <p>Dans le cadre de la modernisation du parc, pour le confort du personnel, des animaux et des visiteurs, les gradins des Perroquets ont été entièrement refaits à neufs, ce qui permettra cette année la réorganisation du spectacle des Perroquets !</p>
                    <p>Amazones à ailes oranges, aras bleu et jaune, youyous du Sénégal, aras chloroptères, grands eclectus, gris du Gabon et autres Pscittacidés survolent le public dans un ballet aérien ludique, pédagogique et haut en couleur !</p>
                    <p><strong><u>Spectacle de dauphins "L'inteligence marine" :</u></strong></p>
                    <p>Vous assistez à une représentation préparée par les équipes de soigneurs du bassin, soutenue par des musiques spécialement composées pour l’occasion : une approche fascinante sur les richesses de la Méditerranée !</p>
                
                    <h1><img src="images/arbre.jpg" alt="x" class="ico_categorie" /><u>Des ateliers</u></h1>
                    <p>Venez vous immerger dans la vie de notre parc, cotoyer nos amis les animaux dans de nombreuses activités ludiques.</p>
                    <p><strong><u>Soigneur d'un jour "dans la peau d'un pro : s'adresse exclusivement aux amoureux des animaux"</u></strong></p>
                    <p>A Zooland, il n'y a pas que les enfants qui ont le droit de jouer aux soigneurs en herbe. </p>
                    <p>Les plus grands, entendez par là de 16 à 99 ans !, peuvent aussi se mettre dans la peau d'un soigneur animalier et vivre des moments forts en émotions et de complicités avec les animaux et leurs soigneurs ! </p>

                    <p>Après avoir enfilé la tenue de soigneur animalier, direction les coulisses du plus grand parc animalier d'Auvergne Rhône-Alpes et plus précisément le resto des animaux. 
                    Là, vous rencontrerez un soigneur animalier bien particulier : le magasinier. </p>
                    <p>C'est lui qui est chargé de préparer les rations de nourriture de chaque animal sauvage. Il vous dévoilera les plats favoris des primates, des carnivores, des girafes, éléphants ... et des manchots !</p>
                    <p>Direction ensuite l'Espace aquatique ou la maison des otaries pour la découverte de manière privilégiée et plus intime d'une autre activité spécifique du soigneur animalier : l'entraînement médical. 
                    <p>Des gestes quotidiens dispensés chaque jour par le soigneur animalier afin d'habituer ces animaux sauvages d'être manipulés et soignés sans recourir à l'anesthésie. </p>
                    <p>Passez une demie-journée dans les coulisses du parc aux côtés d’un soigneur-animateur</p>
                    <p><strong><u>Soigneur junior "Découvrir les coulisses : réservée aux enfants de 10 à 17 ans</u></strong></p>
                    <p>Durant deux heures vos enfants, accompagnés de nos éducateurs pourront se rendre dans les coulisses du parc afin de suivre le quotidien d'un soigneur animalier. Peut-être l'occasion de voir naitre de nouvelles vocations, ou d'en confirmer certaine ?</p>
                    
                    <p><strong><u>Soigneur en herbe "A la découverte des singes : réservée aux enfants de 6 à 10 ans</u></strong></p>
                    <p>Activité pour les enfants souhaitant découvrir le monde primates. Vos enfants rencontreront les animaux et auront l'occasion de nourrir les animaux qu'ils viendront d'étudier.</p>
                </article>
                
                   
            </section>
			
			
            <footer>
                <div id="tweet">
                    <h1><u>Notre dernier article</u></h1>
                    <p>Une première pour notre parc.</p>
                    <p>Pumba le lionceau blanc est née !</p>
                    <p>Le 26 Janvier à 00h52</p>
                    <p><img src="images/lion_blanc.jpg" alt="lionceau" /></p>
                    
                </div>
	<p class="espaco">...<p>
                <div id="mes_photos">
                    <h1><u> Nos espèces</u></h1>
                    <p class="espaco">...<p>
                    <p><img src="images/5.png" alt="Photographie" /><img src="images/4.png" alt="Photographie" /> <br /> 
                    <img src="images/2.png" alt="Photographie" /><img src="images/6.jpg" alt="Photographie" /></p>
                </div>

                <div id="mes_amis">
                    <h1><u>Nos consultants</u></h1>
                    <div id="listes_amis">
                        <ul>
                            <li>Marine</li>
                            <li>Sophie</li>
                            <li>Fatma</li>
                            <li>Davit</li>
                            
                        </ul>
                        <ul>
                            
                        <li>chef de projet</li> 
                        <li>chargé de la finance</li>
                        <li>chargé de veille</li>
                        <li>chargé de développement</li>
                            
                        </ul>
                    </div>
                    <div id="réseaux">
                        <p class="espaco">...</>
                        <p class="espaco">...</><img src="images/facebook.png" alt="Facebook" /> <img src="images/twitter.png" alt="Twitter"/> <img src="images/vimeo.png" alt="Vimeo" /> <img src="images/insta.jpg" alt="Insta" /></p>
                        
                        
                    </div>
                </div>
            </footer>
        </div>
    </body>
</html>